// Copyright (c) 2025-2026 chaunsin
// SPDX-License-Identifier: MIT

package ncmctl

import (
	"bytes"
	"context"
	"errors"
	"fmt"
	"net/http"
	"net/url"
	"os"

	"codeberg.org/sbinet/mozcookie"
	"github.com/spf13/cobra"

	"github.com/chaunsin/netease-cloud-music/api"
	"github.com/chaunsin/netease-cloud-music/api/weapi"
	"github.com/chaunsin/netease-cloud-music/pkg/log"
	"github.com/chaunsin/netease-cloud-music/pkg/utils"
)

var cookieLongUse = `Import Cookie content from --file or an optional positional string.
The input must contain MUSIC_U and may use header, JSON, or Netscape format.
With --format unset, the command tries those formats automatically.
--file takes precedence when both inputs are provided.
Prefer a protected file because direct values may remain in shell history.
The examples below preserve the supported export shapes but are not reusable credentials.
Replace every placeholder with fresh values exported from an authenticated browser session.

Cookie-based login supports the following three content modes.

The --format parameter can be used for configuration.

* header

Content Examples:

uid=123456; PHPSESSID=28f2d88ee9322cfd2e4f1e; csrftoken=abcdef123456; logged_in=true
MUSIC_U=<redacted>; __csrf=<redacted>

* netscape

Content Examples:

# Netscape HTTP Cookie File
# This file was generated by Cookie Editor https://chromewebstore.google.com/detail/cookie-editor/ookdjilphngeeeghgngjabigmpepanpl
.music.163.com	TRUE	/	TRUE	1893456000	MUSIC_U	<redacted>
.163.com	TRUE	/	FALSE	1775732160	_ntes_nuid	47eabde2b621ff2848404b66e558ca99
.music.163.com	TRUE	/	FALSE	1775732161	NMTID	00Onhjq5uaKix1KMUPyrlAkMRkv_VgAAAGVZfK6jQ
.music.163.com	TRUE	/	FALSE	1780457981	WEVNSM	1.0.0
.music.163.com	TRUE	/	FALSE	1775732750	WNMCID	hyazcy.1741172750877.01.0

Reference:

- https://curl.se/rfc/cookie_spec.html
- http://justsolve.archiveteam.org/wiki/Netscape_cookies.txt
- https://docs.cyotek.com/cyowcopy/1.10/netscapecookieformat.html

* json

Content Examples:

[
  {
    "domain": ".music.163.com",
    "expirationDate": 1893456000,
    "hostOnly": false,
    "httpOnly": true,
    "name": "MUSIC_U",
    "path": "/",
    "sameSite": "unspecified",
    "secure": true,
    "session": false,
    "storeId": "0",
    "value": "<redacted>"
  },
  {
    "domain": ".163.com",
    "expirationDate": 1775732160.825451,
    "hostOnly": false,
    "httpOnly": false,
    "name": "_ntes_nnid",
    "path": "/",
    "sameSite": "unspecified",
    "secure": false,
    "session": false,
    "storeId": "0",
    "value": "47eabde2b621ff2848404b66e558ca99,1741172160825"
  },
  {
    "domain": ".163.com",
    "expirationDate": 1775732160.825588,
    "hostOnly": false,
    "httpOnly": false,
    "name": "_ntes_nuid",
    "path": "/",
    "sameSite": "unspecified",
    "secure": false,
    "session": false,
    "storeId": "0",
    "value": "47eabde2b621ff2848404b66e558ca99"
  }
]

* default:

Automatically attempt netscape, json, and header.
`

type loginCookieCmd struct {
	root *Login
	cmd  *cobra.Command
	l    *log.Logger

	File   string
	format string
}

func cookie(root *Login, l *log.Logger) *cobra.Command {
	c := &loginCookieCmd{
		root: root,
		l:    l,
	}
	c.cmd = &cobra.Command{
		Use:   "cookie [cookie]",
		Short: "Log in by importing browser cookies",
		Long:  cookieLongUse,
		Example: "  ncmctl login cookie --file cookie.txt\n" +
			"  ncmctl login cookie --format netscape --file cookies.txt\n" +
			"  ncmctl login cookie 'MUSIC_U=...; __csrf=...'\n" +
			"  ncmctl login cookie --format json --file cookies.json",
		Args: cobra.MaximumNArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			return c.execute(cmd.Context(), args)
		},
	}
	c.addFlags()
	return c.cmd
}

func (c *loginCookieCmd) addFlags() {
	c.cmd.Flags().StringVarP(&c.File, "file", "f", "", "read Cookie content from file (preferred for sensitive values)")
	c.cmd.Flags().StringVar(&c.format, "format", "", "input format: header, json, or netscape (default: auto-detect)")
}

func parseCookieData(data []byte, format string) ([]*http.Cookie, error) {
	parse := func(candidate string) ([]*http.Cookie, error) {
		switch candidate {
		case "json":
			return ParseCookeJson(bytes.NewReader(data))
		case "netscape":
			return mozcookie.Decode(bytes.NewReader(data))
		case "header":
			return http.ParseCookie(string(data))
		default:
			return nil, fmt.Errorf("unsupported cookie format %q", candidate)
		}
	}

	if format != "" {
		cookies, err := parse(format)
		if err != nil {
			return nil, fmt.Errorf("parse %s cookies: %w", format, err)
		}
		return cookies, nil
	}

	var parseErrors []error

	for _, candidate := range []string{"netscape", "json", "header"} {
		cookies, err := parse(candidate)
		if err == nil && len(cookies) > 0 {
			return cookies, nil
		}

		if err != nil {
			parseErrors = append(parseErrors, fmt.Errorf("%s: %w", candidate, err))
		}
	}

	if len(parseErrors) == 0 {
		return nil, errors.New("cookie is empty")
	}
	return nil, fmt.Errorf("detect cookie format: %w", errors.Join(parseErrors...))
}

func (c *loginCookieCmd) execute(ctx context.Context, args []string) error {
	var content string
	if len(args) > 0 {
		content = args[0]
	}

	if c.File == "" && content == "" {
		return errors.New("file is required or imput cookie string")
	}

	if c.format != "" &&
		c.format != "json" &&
		c.format != "netscape" &&
		c.format != "header" {
		return fmt.Errorf("format is not support: %v", c.format)
	}

	log.Debugf("cookie login input: format=%q file=%t positional=%t", c.format, c.File != "", content != "")

	data := []byte(content)

	if c.File != "" {
		file, err := utils.ExpandTilde(c.File)
		if err != nil {
			return fmt.Errorf("ExpandTilde: %w", err)
		}

		c.File = file

		data, err = os.ReadFile(c.File)
		if err != nil {
			return fmt.Errorf("read cookie file: %w", err)
		}
	}

	cookies, err := parseCookieData(data, c.format)
	if err != nil {
		return err
	}

	if len(cookies) == 0 {
		return errors.New("cookie is empty")
	}

	var hasToken bool

	for _, v := range cookies {
		if v.Name == "MUSIC_U" {
			hasToken = true
			break
		}
	}

	if !hasToken {
		return errors.New("cookie not found MUSIC_U value")
	}

	// Parse the domain into a URL (adjust a scheme if needed)
	u, err := url.Parse("https://music.163.com")
	if err != nil {
		return fmt.Errorf("failed to parse domain URL: %w", err)
	}

	cli, err := api.NewClient(c.root.root.Cfg.Network, c.l)
	if err != nil {
		return fmt.Errorf("NewClient: %w", err)
	}
	defer closeAPIClient(ctx, cli)

	cli.SetCookies(u, cookies)

	// 查询登录信息是否成功
	request := weapi.New(cli)

	user, err := request.GetUserInfo(ctx, &weapi.GetUserInfoReq{})
	if err != nil {
		return fmt.Errorf("GetUserInfo: %w", err)
	}

	if err := validateLoginAccount(user); err != nil {
		return err
	}

	c.cmd.Printf("login success: %+v\n", user)
	return nil
}
